apiVersion: v1
kind: ConfigMap
metadata:
  name: p-fb-configmap
  namespace: devops-ramses-configmap
  labels:
    app: pesbuk
data:
  config.php: |
    <?php
    $db_host = "php-pesbuk";
    $db_user = "devopscilsy";
    $db_pass = "1234567890";
    $db_name = "dbsosmed";

    try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>
