apiVersion: v1
kind: Service
metadata:
  name: pesbuk-service
  namespace: devops-ramses-configmap
spec:
  selector:
    app: pesbuk
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
